---
- name: Get root partition name
  ansible.builtin.shell: lsblk {{ target_device }} -ln -o name,fstype | grep btrfs | cut -f 1 -d " "
  register: root_partition_output

- name: Save root partition name
  ansible.builtin.set_fact:
    root_partition: '/dev/{{ root_partition_output.stdout }}'

- name: Get boot partition name
  ansible.builtin.shell: lsblk {{ target_device }} -ln -o name,fstype | grep vfat | cut -f 1 -d " "
  register: boot_partition_output

- name: Save boot partition name
  ansible.builtin.set_fact:
    boot_partition: '/dev/{{ boot_partition_output.stdout }}'

- name: Get swap partition name
  ansible.builtin.shell: lsblk {{ target_device }} -ln -o name,fstype | grep swap | cut -f 1 -d " "
  register: swap_partition_output

- name: Save swap partition name
  ansible.builtin.set_fact:
    swap_partition: '/dev/{{ swap_partition_output.stdout }}'
