---
- name: Copy the mounted file systems table
  ansible.builtin.shell: cp --remove-destination /etc/mtab /mnt/etc/mtab

- name: Generate target fstab
  ansible.builtin.shell: genfstab -U /mnt >> /mnt/etc/fstab

- name: Copy dns config to chrooted env
  ansible.builtin.shell: cp /etc/resolv.conf /mnt/etc/resolv.conf

- name: Bind the pseudo-filesystems for chroot
  ansible.builtin.shell: |
    mount -o bind /dev /mnt/dev
    mount -o bind /dev/pts /mnt/dev/pts
    mount -o bind /proc /mnt/proc
    mount -o bind /sys /mnt/sys
    mount -o bind /sys/firmware/efi/efivars /mnt/sys/firmware/efi/efivars
  ignore_errors: yes
